---
title: "RootsandSoilC Notes"
author: "Ranae Dietzel"
date: "September 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Checklist for giving to coauthors  
- [] Address Castellano's comments  
- [] Improve figures for smaller size  
- [] *Incorporate literature*  
- [x] Write Abstract
- [x] Fix all the tables, really - okay for now - table 3 is from excel???
- [x] Maize planting dates and management
- [] Make bibliography

Many comparisons of perennial and annual cropping systems have failed to find differences in soil organic C levels, especially at deeper depths (Omonde et al. 2006, check dissertation for others).  O'Brien at el. (2010) found soil organic C levels to decrease below 10 cm after the reconstruction of prairie systems.  Such results are often attributed to C saturation     
     
     

Need citations for: 

Soil organic matter losses
Roles of increases aeration
         Addition of fertilizer
         Changes in residue amount and quality  
Slower increases at deeper depths than shallower depths may be indicative that accumulation there is more dependent upon the carryover of roots from previous years than at shallower depths.  

Root growth slows as systems become more established.  


##Omonode 2006
    - After six years, organic C differences (1 m) between corn and prairie in only 30% of sites

Gebhart 1994 The CRP increases soil organic carbon. J. Soil Water Conserv. 49, 488-492

Zan et al. 2001 Carbon sequestration in perennial bioenergy, annual corn and uncultivated systems in
southern Quebec. Agric. Ecosys. Environ. 86, 35-144

Dahlman and Kucera, 1965

Garten and Wullschleger 2000 Soil carbon inventories under a bioenergy crop (switchgrass): measurement limitations. J. Environ. Qual. 28, 1359-1365

Rumpel, C., Kogel-Knabner, I., Bruhn, F., 2002. Vertical distribution, age,and chemical composition of organic carbon in two forest soils of different pedogenesis. Organic Geochem. 33, 1131-1142.

    - Maybe high prairie root C:N ratios is why we don't see huge increases after restoration - not just       soil texture  

Ma, Z.,Wood, C.A., Bransby, D.J., 2000c. Soil management impacts on soil carbon sequestration by switchgrass. Biomass Bioenergy 18, 469-477. - *N fertilization leads to faster turnover in grasses*  

Lemaire, G., Wilkins, R., Hodgson, J., 2005. Challenges for grassland science: management research priorities. Agric. Ecosys. Environ. 108, 99-108.




 
 
 
 
